name: 'Deploy Release to Netlify'

on:
  release:
    types: [published]

jobs:
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=.
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
