name: 'Manual - Deploy to Netlify'

on:  workflow_dispatch

jobs:
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Update version.js
        run: |
          echo "document.querySelector('.footerMiddle').innerHTML = 'Manual deploy from main';" >> js/version.js
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=. --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
