name: TEST - Write Version to File
on:  workflow_dispatch

jobs:
  write-version:
    runs-on: ubuntu-latest
    name: Write Version to File
    steps:
    - uses: actions/checkout@master
    - name: Show default environment variables
      run: |
          echo "GITHUB_REF is: $GITHUB_REF"
          echo "GITHUB_REF_NAME is: $GITHUB_REF_NAME"
