name: TEST - Write Version to File
on:  workflow_dispatch

jobs:
  write-version:
    runs-on: ubuntu-latest
    name: TEST
    steps:
    - uses: actions/checkout@master
    - name: Update version.js
      run: |
          echo "document.querySelector('.footerMiddle').innerHTML = '$GITHUB_REF_NAME';" >> js/version.js
